LIBRE_EMAIL = "m.breur@upcmail.nl"
LIBRE_PASSWORD = "#RoTTerdam010!"

[postgres]
host = "db.mtfmpzdnkemsbxpbbmjm.supabase.co"
port = 6543
username = "postgres"
password = "yfevxmpu6kdRMlkW"
database = "postgres"