LIBRE_EMAIL = "m.breur@upcmail.nl"
LIBRE_PASSWORD = "#RoTTerdam010!"

[postgres]
host = "aws-0-eu-central-1.pooler.supabase.co"
port = 6543
username = "postgres.mtfmpzdnkemsbxpbbmjm"
password = "yfevxmpu6kdRMlkW"
database = "postgres"